### ISSUE TITLE
W/IInputConnectionWrapper( 5266): flutter issue on android 

### ISSUE THREAD

**Issue by Nasirdev74** [TimerniDevelopers/tikarboi_app#1]
when opening the phone keyboard, the flutter streaming messages in the console. console messages: 
`
W/IInputConnectionWrapper( 5266): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5266): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5266): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5266): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5266): endBatchEdit on inactive InputConnection
W/TextInputPlugin( 5266): Changing the content within the the composing region may cause the input method to behave strangely, and is therefore discouraged. See https://github.com/flutter/flutter/issues/78827 for more details
W/TextInputPlugin( 5266): Changing the content within the the composing region may cause the input method to behave strangely, and is therefore discouraged. See https://github.com/flutter/flutter/issues/78827 for more details
W/TextInputPlugin( 5266): Changing the content within the the composing region may cause the input method to behave strangely, and is therefore discouraged. See https://github.com/flutter/flutter/issues/78827 for more details
`

**Comment by timerni-nasir** [comment]
This issue is solved.
