### ISSUE TITLE
enormous patient registration input field height. 

### ISSUE THREAD

**Issue by Nasirdev74** [TimerniDevelopers/tikarboi_app#2]
the height of input field should be decreased. 

![image](https://user-images.githubusercontent.com/85624741/122641659-8bd7ba00-d128-11eb-8c6b-d02bfd2063be.png)

**Comment by timerni-nasir** [comment]
This issue has been solved. 

![image](https://user-images.githubusercontent.com/84341808/122645315-bbdc8880-d13b-11eb-90b0-eab0a5951211.png)
